### ISSUE TITLE
Running a discovery - Waiting for homieEnd

### ISSUE THREAD

**Issue by autolog** [GledholtHall/beta-3#11]
I have run discovery and am getting this error:

> dev:2162022-01-24 18:14:40.061 infoMQTT> Waiting for homieEnd .. - but it appears there is no queue:-) 
> dev:2162022-01-24 18:14:40.057 warnMQTT> Waiting for  homieEnd  [homieEnd]
> dev:2162022-01-24 18:14:20.063 infoMQTT> Waiting for homieEnd .. - but it appears there is no queue:-) 
> dev:2162022-01-24 18:14:20.058 warnMQTT> Waiting for  homieEnd  [homieEnd]
> dev:2162022-01-24 18:14:00.058 infoMQTT> Waiting for homieEnd .. - but it appears there is no queue:-) 
> dev:2162022-01-24 18:14:00.053 warnMQTT> Waiting for  homieEnd  [homieEnd]
> dev:2162022-01-24 18:13:40.060 infoMQTT> Waiting for homieEnd .. - but it appears there is no queue:-) 
> dev:2162022-01-24 18:13:40.054 warnMQTT> Waiting for  homieEnd  [homieEnd]
> dev:2162022-01-24 18:13:36.990 infoMQTT> ============= 1 homie entries for device indigo-devices =============
> dev:2162022-01-24 18:13:36.834 infoMQTT> MQTT subscribing to: homie/home-1/$pacing
> dev:2162022-01-24 18:13:36.807 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/$type
> dev:2162022-01-24 18:13:36.778 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/+/$unit
> dev:2162022-01-24 18:13:36.769 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/$properties
> dev:2162022-01-24 18:13:36.740 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/dim/$format
> dev:2162022-01-24 18:13:36.736 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/$name
> dev:2162022-01-24 18:13:36.727 infoMQTT> MQTT subscribing to: homie/indigo-devices/$nodes
> dev:2162022-01-24 18:13:36.713 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/dim
> dev:2162022-01-24 18:13:36.695 infoMQTT> MQTT subscribing to: homie/indigo-devices/+/onoff
> dev:2162022-01-24 17:41:23.342 infoMQTT> MQTT subscribing to: homie/home-1/+/+/+/set
> dev:2162022-01-24 17:41:23.322 infoMQTT> MQTT subscribing to: homie/home-1/+/+/set
> dev:2162022-01-24 17:41:22.235 infoMQTT> homie discovery is for device: indigo-devices
> dev:2162022-01-24 17:41:17.985 warnMQTT> ## Restarted ##
> dev:2162022-01-24 17:41:17.981 infoMQTT> Log level set to 2
> dev:2162022-01-24 17:41:07.195 infoMQTT> MQTT subscribing to: homie/home-1/$implementation/heartbeat
> dev:2162022-01-24 17:41:07.190 infoMQTT> Connected to MQTT broker tcp://192.168.1.8:1883
> dev:2162022-01-24 17:41:06.177 infoMQTT> Broker: Status: Connection succeeded
> dev:2162022-01-24 17:41:05.864 infoMQTT> Connecting with 'clean' session as Hubitat_home-1 to MQTT broker tcp://192.168.1.8:1883
> dev:2162022-01-24 17:41:05.860 infoMQTT> MQTT> client beta 3e pre6 home-1
> dev:2162022-01-24 17:41:05.817 infoMQTT> Resetting MQTT connection
> dev:2162022-01-24 17:41:05.813 infoMQTT> Disconnected MQTT
> dev:2162022-01-24 17:41:05.603 errororg.codehaus.groovy.runtime.metaclass.MissingMethodExceptionNoStack: No signature of method: user_driver_ukusa_MQTT_Client_485.setmyhub() is applicable for argument types: (java.lang.String) values: [false] (method setmyhub)
> 

The device being searched for is:
![MQTT_Explorer_Definitions_V4](https://user-images.githubusercontent.com/11138074/150842634-0305acae-9c6d-46fa-9236-20e2d642827f.png)

It is present in the list of HE devices but turning it on or off doesn't cause MQTT to publish the changes AFAICS.

I guess maybe, because it is waiting for homieEnd?

**Comment by GledholtHall** [comment]
After each wildcard request for devices my app sends a 'pacing' message - in this case homieEnd.  It is a payload post to a pacing topic.  It is the only way I can tell that I have received all the subscribed message from a wildcarded topic as that pacing message always comes in last.   

I don't think you have updated to the latest versions though - you need to run beta 3e pre24 for the app and beta3e pre 22 for the client - your client appears to be beta 3d.  Do you have access to beta 3e ?

`MQTT> client beta 3e pre6 home-1`

**Comment by autolog** [comment]
I didn't realise (or more likely remember) that I needed the Client as well. So no I haven't got access to it AFAIK.
What is the process to update to the new versions(APP & Client), I obviously haven't done it correctly which may invalidate the error reports I sent through?

**Comment by GledholtHall** [comment]
Both the beta 3e app and the MQTT client device driver are available here in this repository

**Comment by autolog** [comment]
Resolved in 25/1/22 build. :)
