### ISSUE TITLE
Connecting C7 to Test MQTT Broker

### ISSUE THREAD

**Issue by autolog** [GledholtHall/beta-3#22]
I have succssfully connected Indigo to the private MQTT broker an published the topics Indigo is creating for device discovery in HE.

I have tried connecting my C7 to the broker in order that you can see the topics published by HE.

The C7 appaers to connect to the broker but publsihing devices is not working. I attach the App and Driver logs FYI:

> MQTT Child Driver Log:
> 
> dev:4362022-02-03 12:34:42.980 infoMQTT> MQTT subscribing to: homie/indigo-1/+/$name
> dev:4362022-02-03 12:34:34.589 infoMQTT> ============= 5 homie entries for device indigo-1 =============
> dev:4362022-02-03 12:34:34.236 infoMQTT> MQTT subscribing to: homie/home-1/$pacing
> dev:4362022-02-03 12:34:34.213 infoMQTT> MQTT subscribing to: homie/indigo-1/+/+/$unit
> dev:4362022-02-03 12:34:34.163 infoMQTT> MQTT subscribing to: homie/indigo-1/+/$type
> dev:4362022-02-03 12:34:34.132 infoMQTT> MQTT subscribing to: homie/indigo-1/+/dim/$format
> dev:4362022-02-03 12:34:34.086 infoMQTT> MQTT subscribing to: homie/indigo-1/+/$properties
> dev:4362022-02-03 12:34:34.050 infoMQTT> MQTT subscribing to: homie/indigo-1/+/dim
> dev:4362022-02-03 12:34:34.009 infoMQTT> MQTT subscribing to: homie/indigo-1/$nodes
> dev:4362022-02-03 12:34:33.992 infoMQTT> MQTT subscribing to: homie/indigo-1/+/onoff
> dev:4362022-02-03 12:34:33.380 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-1921277469/onoff
> dev:4362022-02-03 12:34:33.332 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-99417865/onoff
> dev:4362022-02-03 12:34:33.257 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-99417865/dim
> dev:4362022-02-03 12:34:33.204 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-897702736/onoff
> dev:4362022-02-03 12:34:33.127 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-897702736/dim
> dev:4362022-02-03 12:34:33.089 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-1403695954/onoff
> dev:4362022-02-03 12:34:33.006 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-1403695954/dim
> dev:4362022-02-03 12:34:32.976 infoMQTT> MQTT subscribing to: homie/indigo-1/dev-1333137217/onoff
> dev:4362022-02-03 12:34:32.913 infoMQTT> homie discovery is for device: indigo-1
> dev:4362022-02-03 12:34:19.367 infoMQTT> MQTT subscribing to: homie/home-1/+/+/+/set
> dev:4362022-02-03 12:34:19.333 infoMQTT> MQTT subscribing to: homie/home-1/+/+/set
> dev:4362022-02-03 12:34:18.378 infoMQTT> homie discovery is for device: indigo-1
> dev:4362022-02-03 12:34:15.576 warnMQTT> ## Restarted ##
> dev:4362022-02-03 12:34:15.571 infoMQTT> Log level set to 2
> dev:4362022-02-03 12:34:05.224 infoMQTT> Connected to MQTT broker tcp://82.12.193.27:8883
> dev:4362022-02-03 12:34:04.218 infoMQTT> Broker: Status: Connection succeeded
> dev:4362022-02-03 12:34:03.852 infoMQTT> Connecting with 'clean' session as Hubitat_home-1 to MQTT broker tcp://82.12.193.27:8883
> dev:4362022-02-03 12:34:03.846 infoMQTT> MQTT> client beta 3e pre 26 home-1
> dev:4362022-02-03 12:34:03.820 infoMQTT> HAIn Discovery is false
> dev:4362022-02-03 12:34:03.808 infoMQTT> Resetting MQTT connection
> dev:4362022-02-03 12:34:03.803 infoMQTT> Disconnected MQTT
> 
> MQTT App Log:
> 
> app:2982022-02-03 12:36:04.369 errorMQTT broker lost pacing response for [homieEnd]
> app:2982022-02-03 12:34:35.671 warnMQTT: Already in dropdown list:OnOff dev-1333137217
> app:2982022-02-03 12:34:33.978 infoMQTT: ================ Starting homie Discovery =================
> app:2982022-02-03 12:34:33.485 infoMQTT: Initialise exit
> app:2982022-02-03 12:34:32.970 infoMQTT: Subscribing to 8 individual device topics
> app:2982022-02-03 12:34:32.962 warnMQTT: AërQ - Temperature no event handler available or registered for: Sensor
> app:2982022-02-03 12:34:32.954 warnMQTT: AërQ - Temperature no event handler available or registered for: Battery
> app:2982022-02-03 12:34:32.944 warnMQTT: AërQ - Temperature no event handler available or registered for: Telnet
> app:2982022-02-03 12:34:32.938 warnMQTT: AërQ - Temperature no event handler available or registered for: Notification
> app:2982022-02-03 12:34:32.929 warnMQTT: AërQ - Temperature no event handler available or registered for: Actuator
> app:2982022-02-03 12:34:32.863 infoMQTT: Subscribing to virtuals
> app:2982022-02-03 12:34:32.824 infoMQTT: HE device publishing to MQTT has completed in 14 secs 
> app:2982022-02-03 12:34:32.780 infoMQTT: [o] Unknown Category for type released reported by device Study Scene Switch 1
> app:2982022-02-03 12:34:32.734 infoMQTT: [o] Unknown Category for type doubleTapped reported by device Study Scene Switch 1
> app:2982022-02-03 12:34:32.689 infoMQTT: [o] Unknown Category for type pushed reported by device Study Scene Switch 1
> app:2982022-02-03 12:34:32.643 infoMQTT: [o] Unknown Category for type numberOfButtons reported by device Study Scene Switch 1
> app:2982022-02-03 12:34:32.587 infoMQTT: [o] Unknown Category for type battery reported by device Study Scene Switch 1
> app:2982022-02-03 12:34:32.146 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:32.141 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:31.690 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:31.686 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:31.318 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:31.314 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:30.920 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:30.916 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:30.528 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:30.524 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:30.122 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:30.117 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:29.750 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:29.745 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:29.624 warnMQTT: Ignoring null for  Study INNR Led Strip value null
> app:2982022-02-03 12:34:28.523 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:28.518 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:28.151 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:28.146 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:27.480 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:27.476 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:27.433 infoMQTT: [o] Unknown Category for type released reported by device Master Bedroom Scene Switch 2
> app:2982022-02-03 12:34:27.388 infoMQTT: [o] Unknown Category for type doubleTapped reported by device Master Bedroom Scene Switch 2
> app:2982022-02-03 12:34:27.342 infoMQTT: [o] Unknown Category for type pushed reported by device Master Bedroom Scene Switch 2
> app:2982022-02-03 12:34:27.297 infoMQTT: [o] Unknown Category for type numberOfButtons reported by device Master Bedroom Scene Switch 2
> app:2982022-02-03 12:34:27.241 infoMQTT: [o] Unknown Category for type battery reported by device Master Bedroom Scene Switch 2
> app:2982022-02-03 12:34:27.171 infoMQTT: [o] Unknown Category for type released reported by device Master Bedroom Scene Switch 1
> app:2982022-02-03 12:34:27.126 infoMQTT: [o] Unknown Category for type doubleTapped reported by device Master Bedroom Scene Switch 1
> app:2982022-02-03 12:34:27.080 infoMQTT: [o] Unknown Category for type pushed reported by device Master Bedroom Scene Switch 1
> app:2982022-02-03 12:34:27.014 infoMQTT: [o] Unknown Category for type numberOfButtons reported by device Master Bedroom Scene Switch 1
> app:2982022-02-03 12:34:26.958 infoMQTT: [o] Unknown Category for type battery reported by device Master Bedroom Scene Switch 1
> app:2982022-02-03 12:34:25.149 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:25.144 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:25.044 infoMQTT: [o] Unknown Category for type presence reported by device Study Socket Elgato Key Light
> app:2982022-02-03 12:34:24.397 infoMQTT: [t] Unknown category for attribute #switch# reported by device Study Thermostat
> app:2982022-02-03 12:34:24.020 infoMQTT: [t] Unknown category for attribute #checkInterval# reported by device Study Thermostat
> app:2982022-02-03 12:34:23.784 infoMQTT: [t] Unknown category for attribute #batteryLastReplaced# reported by device Study Thermostat
> app:2982022-02-03 12:34:23.576 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:23.572 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:22.546 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:22.541 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:21.548 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:21.544 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:19.735 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:19.731 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:19.464 errorMQTT: isMQTT is null
> app:2982022-02-03 12:34:19.459 warnMQTT: LoopAll dev is myName
> app:2982022-02-03 12:34:19.395 infoMQTT: Resynch MQTT device states and HA discovery topics
> app:2982022-02-03 12:34:18.961 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:18.764 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:18.704 warnMQTT: Unknown property value checkInterval
> app:2982022-02-03 12:34:18.586 warnMQTT: Unknown property value ultravioletIndex
> app:2982022-02-03 12:34:18.571 warnMQTT: Unknown property value tamper
> app:2982022-02-03 12:34:18.555 warnMQTT: Unknown property value powerSource
> app:2982022-02-03 12:34:18.420 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:18.370 infoMQTT: Starting HE device publishing to MQTT for 22 HE devices with 0 attributes
> app:2982022-02-03 12:34:17.373 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:16.984 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:16.833 warnMQTT: Unknown property value checkInterval
> app:2982022-02-03 12:34:16.527 warnMQTT: Unknown property value ultravioletIndex
> app:2982022-02-03 12:34:16.495 warnMQTT: Unknown property value tamper
> app:2982022-02-03 12:34:16.464 warnMQTT: Unknown property value powerSource
> app:2982022-02-03 12:34:15.992 warnMQTT: Unknown property value pressure
> app:2982022-02-03 12:34:05.253 infoMQTT: MQTT reports status of Connect
> app:2982022-02-03 12:34:03.686 infoMQTT: Waiting for MQTT connection: false
> app:2982022-02-03 12:34:03.625 infoMQTT: Standard Logging
> app:2982022-02-03 12:34:03.552 infoMQTT: initialising with App count 0
> app:2982022-02-03 12:34:03.514 infoMQTT: Hubitat hub name is : home-1
> app:2982022-02-03 12:34:03.505 infoMQTT: MQTT Client driver present
> app:2982022-02-03 12:34:03.397 infoMQTT: Removing unused atomicState variables
> app:2982022-02-03 12:34:03.032 infoMQTT: MQTT Updated

**Comment by autolog** [comment]
Hi Kevin,
Actually, I suspect maybe I should have requested authorisation for a node of home-1 under the homie node as I can't publish to the home-1 node using MQTT Explorer whilst I can alter topics under indigo-1. If I am correct, can you authorise that node and I will run this again for you. :)

**Comment by autolog** [comment]
Also, note the errors e.g. **app:2982022-02-03 12:34:21.548 errorMQTT: isMQTT is null**. I just realised I am also getting those when connected to my internal broker. I just assumed that they were a result of the remote connection issue. This may need breaking out in a separate issue?

**Comment by GledholtHall** [comment]
I have added homie devices of home-1 and home-2 for you .
I do see 5 nodes that have been created under devices indigo-1 .
