### ISSUE TITLE
Various Virtual Device problems

### ISSUE THREAD

**Issue by EnsuingRequiem** [GledholtHall/beta-3#25]
### Steps to Reproduce

1. Create new virtual device named `[MQTT] Office Sensor` (temp sensor) manually
2. Enable Device
3. Edit Device
4. Attempt ***unsuccessfully*** to set attribute topic to `zigbee2mqtt/basement/office/sensors/wsdcgq11lm/temperature`
(The screen refreshes each time without saving the setting, even if the Next & Done buttons are clicked)
5. Edit Device
6. Click Delete

Result:

Log output
```
[app:938](https://remoteaccess.aws.hubitat.com/logs#app938)2022-06-23 09:12:06.011 am [error](https://remoteaccess.aws.hubitat.com/installedapp/configure/938)java.lang.NullPointerException: Cannot invoke method updateDataValue() on null object on line 293 (method vMQTT)
[app:938](https://remoteaccess.aws.hubitat.com/logs#app938)2022-06-23 09:10:57.528 am [info](https://remoteaccess.aws.hubitat.com/installedapp/configure/938)MQTT: MQTT reports status of Connect
[app:938](https://remoteaccess.aws.hubitat.com/logs#app938)2022-06-23 09:10:31.996 am [error](https://remoteaccess.aws.hubitat.com/installedapp/configure/938)java.lang.NullPointerException: Cannot invoke method updateDataValue() on null object on line 293 (method vMQTT)
[app:938](https://remoteaccess.aws.hubitat.com/logs#app938)2022-06-23 09:10:27.184 am [error](https://remoteaccess.aws.hubitat.com/installedapp/configure/938)java.lang.NullPointerException: Cannot invoke method updateDataValue() on null object on line 293 (method vMQTT)
[app:938](https://remoteaccess.aws.hubitat.com/logs#app938)2022-06-23 09:10:26.756 am [warn](https://remoteaccess.aws.hubitat.com/installedapp/configure/938)MQTT: Deleted virtual device null
```

Relevant MQTT App Settings (note previous attempts at virtual devices did not get purged)

Name | Type | Value
-- | -- | --
vAr_Var_0_MQTT:virtual_[MQTT] Loft Temp_ | text |  
vAr_Var_0_MQTT:virtual_[MQTT] Loft Temp_temperature_Topic | text |  
vAr_Var_0_MQTT:virtual_[MQTT] Office Sensor_ | text |  
vAr_Var_0_MQTT:virtual_[MQTT] Office Sensor_temperature_Topic | text |  
vAr_Var_0_MQTT:virtual_Office Aqara Temp_ | text | basement/office/sensors/wsdcgq11lm/temperature
vAr_Var_0_MQTT:virtual_Office Aqara Temp_temperature_Topic | text | zigbee2mqtt/basement/office/sensors/wsdcgq11lm/temperature
var_VirtualTemperatureSensor | device.VirtualTemperatureSensor |  
virtualDevs | bool | false

### Environment
Name | Data
-- | --
MQTT Broker | Mosquitto (eclipse-mosquitto:2.0.14)
Hubitat |  C-5 version 2.3.2.128
MQTT App | beta 3e pre 29

**Comment by GledholtHall** [comment]
I hope this is now fixed in beta3e Pre30
